### ISSUE TITLE
Интуиция задвоение

### ISSUE THREAD

**Issue by audetv** [terratensor/conceptual-dictionary#5]
https://github.com/audetv/conceptual-dictionary/blob/eb57203db23cef65578a616900013667615af059/dictionary.txt#L12
https://github.com/audetv/conceptual-dictionary/blob/eb57203db23cef65578a616900013667615af059/dictionary.txt#L65

Надо определить куда относится. 12 строка или 65

**Comment by iprst** [comment]
Ко второму варианту, но и он впоследствии будет пересматриваться.
